using PacketEditor.WakfuBot.Packets.ToReceiv.Fight.RunningEffects;
using System;
using System.Collections.Generic;

public class RunningEffectsConstants {
    public static Dictionary<RunningEffectType, Type> Classes = new Dictionary<RunningEffectType, Type> { 
//{RunningEffectType.VARIABLE_EFFECT, typeof(VariableEffect)},
        {RunningEffectType.HP_LOSS, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS, typeof(HPLoss)},
        //{RunningEffectType.HP_LOSS_WITH_KAMAS_WATER, typeof(HPKamas)},
        //{RunningEffectType.HP_LEECH, typeof(HPLeech)},
        //{RunningEffectType.HP_LEECH_FIRE, typeof(HPLeech)},
        //{RunningEffectType.HP_LEECH_EARTH, typeof(HPLeech)},
        //{RunningEffectType.HP_LEECH_WATER, typeof(HPLeech)},
        //{RunningEffectType.HP_LEECH_AIR, typeof(HPLeech)},
        //{RunningEffectType.SET_HP, typeof(SetCharac)},
        //{RunningEffectType.HP_GAIN_WITH_FEEDBACK, typeof(HPGainWithFeedBack)},
        //{RunningEffectType.HP_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.HP_DEBOOST, typeof(CharacDebuff)},
        //{RunningEffectType.HP_LOSS_ACCUMULATION, typeof(HpLossAccumulation)},
        //{RunningEffectType.COPY_CHARAC_MAX, typeof(CopyCharacMax)},
        //{RunningEffectType.HP_GAIN, typeof(HPGain)},
        //{RunningEffectType.HEAL_GAIN, typeof(CharacGain)},
        //{RunningEffectType.HEAL_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.DEATH, typeof(Death)},
        //{RunningEffectType.HP_GAIN_PERCENT_OF_VALUE, typeof(HPGainPercentOfValue)},
        //{RunningEffectType.ACTION_COST, typeof(ActionCost)},
        //{RunningEffectType.AP_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.AP_DEBOOST, typeof(CharacDebuff)},
        //{RunningEffectType.AP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.AP_LEECH, typeof(CharacLeech)},
        //{RunningEffectType.AP_GIFT, typeof(CharacGift)},
        //{RunningEffectType.AP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RES_AP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CHARAC_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CHARAC_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.MP_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.MP_DEBOOST, typeof(CharacDebuff)},
        //{RunningEffectType.MP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.MP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.MP_LEECH, typeof(CharacLeech)},
        //{RunningEffectType.RES_MP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.SPELL_BOOST_LEVEL, typeof(SpellGain)},
        //{RunningEffectType.HP_LOSS_WITH_REBOUND, typeof(HPLossEffectRebound)},
        //{RunningEffectType.HP_EARTH_LOSS_WITH_REBOUND, typeof(HPLossEffectRebound)},
        //{RunningEffectType.HP_FIRE_LOSS_WITH_REBOUND, typeof(HPLossEffectRebound)},
        //{RunningEffectType.HP_WATER_LOSS_WITH_REBOUND, typeof(HPLossEffectRebound)},
        //{RunningEffectType.HP_AIR_LOSS_WITH_REBOUND, typeof(HPLossEffectRebound)},
        //{RunningEffectType.HP_EXCHANGE, typeof(HPExchangePercentOfValue)},
        //{RunningEffectType.HP_GAIN_WITH_REBOUND_WATER, typeof(HPGainEffectRebound)},
        //{RunningEffectType.CHARAC_STEAL_WITH_LOSS, typeof(CharacSteal)},
        //{RunningEffectType.AP_LEECH_IN_PERCENT, typeof(CharacLeechInPercent)},
        //{RunningEffectType.WP_LEECH_IN_PERCENT, typeof(CharacLeechInPercent)},
        //{RunningEffectType.DMG_LEECH_IN_PERCENT, typeof(CharacLeech)},
        //{RunningEffectType.RES_LEECH_IN_PERCENT, typeof(CharacLeech)},
        //{RunningEffectType.MP_LEECH_IN_PERCENT, typeof(CharacLeechInPercent)},
        //{RunningEffectType.HP_GAIN_WITH_REBOUND_AIR, typeof(HPGainEffectRebound)},
        //{RunningEffectType.RES_HEAL_GAIN, typeof(CharacGain)},
        //{RunningEffectType.RES_BACK_GAIN, typeof(CharacGain)},
        //{RunningEffectType.RES_HEAL_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.WP_LEECH, typeof(CharacLeech)},
        //{RunningEffectType.INIT_LEECH, typeof(CharacLeech)},
        //{RunningEffectType.RES_GAIN_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.RES_FIRE_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.RES_WATER_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.RES_EARTH_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.RES_AIR_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.RES_LOSS_IN_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.RES_EARTH_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.RES_FIRE_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.RES_WATER_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.RES_AIR_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.DMG_GAIN_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.DMG_FIRE_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.DMG_EARTH_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.DMG_WATER_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.DMG_AIR_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.FINAL_DMG_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.FINAL_RES_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.FINAL_RES_IN_PERCENT_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.FINAL_DMG_IN_PERCENT_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.DMG_LOSS_IN_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.DMG_FIRE_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.DMG_EARTH_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.DMG_WATER_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.DMG_AIR_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.PUNISHMENT, typeof(Punishment)},
        //{RunningEffectType.DAMAGES_REBOUND_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.DAMAGES_ABSORB_IN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.LIFE_STOLEN_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CRITICAL_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CC_GAIN, typeof(CharacGain)},
        //{RunningEffectType.EC_GAIN, typeof(CharacGain)},
        //{RunningEffectType.AGILITY_GAIN, typeof(CharacGain)},
        //{RunningEffectType.AGILITY_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.STRENGTH_GAIN, typeof(CharacGain)},
        //{RunningEffectType.STRENGTH_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.INTELLIGENCE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.INTELLIGENCE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.LUCK_GAIN, typeof(CharacGain)},
        //{RunningEffectType.LUCK_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RANGE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.RANGE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.PROSPECTION_GAIN, typeof(CharacGain)},
        //{RunningEffectType.PROSPECTION_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.WISDOM_GAIN, typeof(CharacGain)},
        //{RunningEffectType.WISDOM_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.FEROCITY_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.FUMBLE_RATE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.INIT_GAIN, typeof(CharacGain)},
        //{RunningEffectType.INIT_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.TACKLE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.TACKLE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.DODGE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.DODGE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.BACKSTAB_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.BACKSTAB_BONUS_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.MECHANISM_MASTERY, typeof(CharacGain)},
        //{RunningEffectType.BONUS_TRAP, typeof(CharacGain)},
        //{RunningEffectType.BONUS_SUMMON, typeof(CharacGain)},
        //{RunningEffectType.WP_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.WP_DEBOOST, typeof(CharacDebuff)},
        //{RunningEffectType.WP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.WP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.WP_STEAL, typeof(CharacSteal)},
        //{RunningEffectType.RAISE, typeof(Raise)},
        //{RunningEffectType.VITALITY_GAIN, typeof(CharacGain)},
        //{RunningEffectType.VITALITY_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.SKIP_TURN, typeof(PropertyApply)},
        //{RunningEffectType.REDUCE_RANGE_TO_CAC, typeof(PropertyApply)},
        //{RunningEffectType.ROOTED, typeof(PropertyApply)},
        //{RunningEffectType.IMMUNE_TO_MP_LOSS, typeof(PropertyApply)},
        //{RunningEffectType.INVISIBLE, typeof(PropertyApply)},
        //{RunningEffectType.INVISIBLE_SUPERIOR, typeof(PropertyApply)},
        //{RunningEffectType.FIGHT_FORBIDDEN, typeof(PropertyApply)},
        //{RunningEffectType.CHANGE_CONTROLLER, typeof(ChangeController)},
        //{RunningEffectType.COWARD, typeof(PropertyApply)},
        //{RunningEffectType.HASTE, typeof(PropertyApply)},
        //{RunningEffectType.STABILIZED, typeof(PropertyApply)},
        //{RunningEffectType.CANT_BE_ATTACKED, typeof(PropertyApply)},
        //{RunningEffectType.CANT_TACKLE, typeof(PropertyApply)},
        //{RunningEffectType.STATE_RESISTANCE, typeof(StateResistance)},
        //{RunningEffectType.NO_FIGHT_XP, typeof(PropertyApply)},
        //{RunningEffectType.SET_MAX_AP_COS, typeof(PropertyApply)},
        //{RunningEffectType.SET_EFFECT_AREA_GRIP, typeof(PropertyApply)},
        //{RunningEffectType.REVEAL_INVISIBLE, typeof(PropertyApply)},
        //{RunningEffectType.UNDEAD, typeof(PropertyApply)},
        //{RunningEffectType.UNTARGETTABLE, typeof(PropertyApply)},
        //{RunningEffectType.IA_DOUBLE_FOCUS, typeof(PropertyApply)},
        //{RunningEffectType.STASIS_1, typeof(PropertyApply)},
        //{RunningEffectType.STASIS_2, typeof(PropertyApply)},
        //{RunningEffectType.STASIS_3, typeof(PropertyApply)},
        //{RunningEffectType.IA_MINIMIZE_FOCUS, typeof(PropertyApply)},
        //{RunningEffectType.RAISE_OUT_OF_COMBAT, typeof(RaiseOutOfCombat)},
        //{RunningEffectType.GROGGY_1, typeof(PropertyApply)},
        //{RunningEffectType.GROGGY_2, typeof(PropertyApply)},
        //{RunningEffectType.GROGGY_3, typeof(PropertyApply)},
        //{RunningEffectType.CRIPPLED_1, typeof(PropertyApply)},
        //{RunningEffectType.CRIPPLED_2, typeof(PropertyApply)},
        //{RunningEffectType.CRIPPLED_3, typeof(PropertyApply)},
        //{RunningEffectType.LAME, typeof(PropertyApply)},
        //{RunningEffectType.EQUIPMENT_KNOWLEDGE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.AP_DEBUFF_POWER, typeof(CharacGain)},
        //{RunningEffectType.MP_DEBUFF_POWER, typeof(CharacGain)},
        //{RunningEffectType.EXTRA_TURN, typeof(PropertyApply)},
        //{RunningEffectType.NO_DEATH, typeof(PropertyApply)},
        //{RunningEffectType.STATE_APPLICATION_BONUS, typeof(StateApplicationBonus)},
        //{RunningEffectType.DONT_BLOCK_LOS, typeof(PropertyApply)},
        //{RunningEffectType.ESCAPE_TACKLE, typeof(PropertyApply)},
        //{RunningEffectType.CANT_TELEPORT, typeof(PropertyApply)},
        //{RunningEffectType.HP_BOOST_IN_PERCENT_FUNCTION_ALLIES_COUNT, typeof(CharacBoostInPercentFunctionAlliesCount)},
        //{RunningEffectType.HP_BOOST_IN_PERCENT, typeof(CharacBoostInPercentFunctionCaster)},
        //{RunningEffectType.HP_GAIN_AIR, typeof(HPGain)},
        //{RunningEffectType.HP_GAIN_EARTH, typeof(HPGain)},
        //{RunningEffectType.HP_GAIN_WATER, typeof(HPGain)},
        //{RunningEffectType.HP_GAIN_FIRE, typeof(HPGain)},
        //{RunningEffectType.WISDOM_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.HP_GAIN_AIR_FOR_CASTER_BASED_ON_TARGET, typeof(HPGainForCasterBasedOnTarget)},
        //{RunningEffectType.HP_GAIN_EARTH_FOR_CASTER_BASED_ON_TARGET, typeof(HPGainForCasterBasedOnTarget)},
        //{RunningEffectType.HP_GAIN_WATER_FOR_CASTER_BASED_ON_TARGET, typeof(HPGainForCasterBasedOnTarget)},
        //{RunningEffectType.HP_GAIN_FIRE_FOR_CASTER_BASED_ON_TARGET, typeof(HPGainForCasterBasedOnTarget)},
        //{RunningEffectType.HP_GAIN_PHYSICAL_FOR_CASTER_BASED_ON_TARGET, typeof(HPGainForCasterBasedOnTarget)},
        //{RunningEffectType.INIT_GAIN_PERCENT_OF_VALUE, typeof(CharacGain)},
        //{RunningEffectType.INIT_LOSS_PERCENT_OF_VALUE, typeof(CharacLoss)},
        //{RunningEffectType.MP_SET_TO_MAX, typeof(SetCharacToMax)},
        {RunningEffectType.PUSH, typeof(Push)},
        {RunningEffectType.PULL, typeof(Pull)},
        {RunningEffectType.TELEPORT_CASTER, typeof(TeleportCaster)},
        //{RunningEffectType.ATTRACT_SIGHT, typeof(ChangeDirection)},
        //{RunningEffectType.STATE_APPLY, typeof(ApplyState)},
        {RunningEffectType.GET_CLOSER, typeof(GetCloser)},
        {RunningEffectType.PULL_ON_CASTER_BACK, typeof(PullTargetBackToCaster)},
        {RunningEffectType.SUMMON, typeof(Summon)},
        //{RunningEffectType.SET_TRAP, typeof(SetTrap)},
        //{RunningEffectType.SPELL_REBOUND, typeof(SpellRebound)},
        //{RunningEffectType.RUNNING_STATE, typeof(StateRunningEffect)},
        //{RunningEffectType.SET_CADRAN, typeof(SetCadran)},
        //{RunningEffectType.SET_HOUR, typeof(SetHourEffectArea)},
        //{RunningEffectType.SET_BEACON, typeof(SetBeacon)},
        //{RunningEffectType.SET_AURA, typeof(SetEffectArea)},
        //{RunningEffectType.SET_GLYPH, typeof(SetEffectArea)},
        //{RunningEffectType.UNSET_AURAS, typeof(UnsetAuras)},
        //{RunningEffectType.SET_BOMB, typeof(SetBombEffectArea)},
        //{RunningEffectType.SEDUCE_MONSTER, typeof(SeduceCreature)},
        //{RunningEffectType.STATE_FORCE_UNAPPLY, typeof(StateDecurse)},
        //{RunningEffectType.SUMMON_SRAM_DOUBLE, typeof(SummonSramDouble)},
        //{RunningEffectType.BRING_BACK, typeof(BringBackToSymbiot)},
        //{RunningEffectType.SUMMON_FROM_SYMBIOT, typeof(SummonFromSymbiot)},
        //{RunningEffectType.SET_AI, typeof(SetAI)},
        //{RunningEffectType.WEAPONATTACK, typeof(WeaponAttack)},
        //{RunningEffectType.AI_GIVE_ORDER, typeof(AIGiveOrder)},
        //{RunningEffectType.AI_GIVE_ORDER_CELL, typeof(AIGiveOrderOnCell)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP, typeof(RunningEffectGroup)},
        //{RunningEffectType.REPELL, typeof(Repell)},
        //{RunningEffectType.UNSUMMON, typeof(Unsummon)},
        //{RunningEffectType.THROW, typeof(Throw)},
        //{RunningEffectType.CARRY, typeof(Carry)},
        //{RunningEffectType.UPDATE_MAX_SEDUCABLE_CREATURES, typeof(UpdateMaximumSeducableCreatures)},
        //{RunningEffectType.SET_AURA_ON_TARGET, typeof(SetAuraOnTarget)},
        //{RunningEffectType.SET_EFFECT_AREA, typeof(SetEffectArea)},
        {RunningEffectType.TELEPORT_TARGET, typeof(TeleportTarget)},
        //{RunningEffectType.RANDOM_RUNNING_EFFECT_GROUP, typeof(RandomRunningEffectGroup)},
        //{RunningEffectType.MAKE_FLEE, typeof(MakeFlee)},
        //{RunningEffectType.APPLY_STATE_FUNCTION_PA_PM_PW, typeof(ApplyStateFunctionPaPmPw)},
        //{RunningEffectType.SPELL_BREAK, typeof(SpellBreak)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_RANDOM_TARGETS, typeof(RunningEffectGroupWithRandomTarget)},
        //{RunningEffectType.APPLY_DEATHTAG, typeof(ApplyState)},
        //{RunningEffectType.SUMMON_IMAGE, typeof(SummonImage)},
        //{RunningEffectType.SET_AREA_WITH_LEVEL_FUNCTION_SPELL, typeof(SetEffectAreaFunctionSpellLevel)},
        //{RunningEffectType.EFFECT_RANDOM_IN_AREA, typeof(RunningEffectGroupEffectRandomInArea)},
        //{RunningEffectType.APPLY_STATE_WITHOUT_NOTIFICATION, typeof(ApplyStateWithoutNotification)},
        //{RunningEffectType.STATE_DECURSE_WITHOUT_NOTIFICATION, typeof(StateDecurseWithoutNotification)},
        //{RunningEffectType.APPLY_STATE_FUNCTION_ACTION_COST, typeof(ApplyStateFunctionActionCost)},
        //{RunningEffectType.APPLY_STATE_FOR_FECA_ARMOR, typeof(ApplyStateForFecaArmor)},
        //{RunningEffectType.REMOVE_FECA_ARMOR, typeof(RemoveFecaArmor)},
        //{RunningEffectType.SET_FECA_GLYPH, typeof(SetEffectArea)},
        //{RunningEffectType.XELORS_DIAL_CHARGE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.XELORS_DIAL_CHARGE_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.SET_AI_WITH_SPELLS_FOR_IA_SERVER, typeof(SetAIWithSpellsForAIServer)},
        //{RunningEffectType.NULL_EFFECT, typeof(NullEffect)},
        //{RunningEffectType.SPLIT_TRIGGER_EFFECT, typeof(SplitTriggerEffect)},
        //{RunningEffectType.NULL_EFFECT_ON_CELL, typeof(NullEffectOnCell)},
        //{RunningEffectType.NULL_EFFECT_NOTIFIED_TO_AI, typeof(NullEffectNotifiedToAI)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_MAX, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_MAX, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_MAX, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_MAX, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_MAX, typeof(HPLoss)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_CURRENT, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_CURRENT, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_CURRENT, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_CURRENT, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_CURRENT, typeof(HPLoss)},
        //{RunningEffectType.DECURSE, typeof(DecurseStandardEffect)},
        {RunningEffectType.EXCHANGE_POSITION, typeof(ExchangePosition)},
        //{RunningEffectType.SPELL_ATTACK, typeof(SpellAttack)},
        //{RunningEffectType.UPDATE_VALUE, typeof(UpdateValue)},
        //{RunningEffectType.KAMA_STEAL, typeof(KamaSteal)},
        //{RunningEffectType.PICK_UP_ITEM, typeof(PickUpItem)},
        //{RunningEffectType.BOOST_SKILL_WITH_SPELL, typeof(BoostSkillWithSpell)},
        //{RunningEffectType.KAMA_SHIELD, typeof(KamaShield)},
        //{RunningEffectType.UPDATE_TARGET_WITH_CARRIER, typeof(UpdateTargetByOther)},
        //{RunningEffectType.VIRTUAL_ARMOR, typeof(VirtualArmor)},
        //{RunningEffectType.REVEAL_INVISIBILITY, typeof(RevealInvisibility)},
        //{RunningEffectType.POISON_AP, typeof(CharacPoison)},
        //{RunningEffectType.POISON_MP, typeof(CharacPoison)},
        //{RunningEffectType.POISON_WP, typeof(CharacPoison)},
        //{RunningEffectType.UPDATE_CASTER_WITH_TARGET, typeof(UpdateCasterByOther)},
        //{RunningEffectType.CONFUSED, typeof(PropertyApply)},
        //{RunningEffectType.IMMUNE_TO_EFFECTS, typeof(PropertyApply)},
        //{RunningEffectType.REMOVE_FIGHT_PROPERTY, typeof(RemoveFightProperty)},
        //{RunningEffectType.APPLY_FIGHT_PROPERTY, typeof(ApplyFightProperty)},
        //{RunningEffectType.POISON_TRIGERRING_VALUE, typeof(TriggeringValuePoison)},
        //{RunningEffectType.APPLY_WORLD_PROPERTY, typeof(ApplyWorldProperty)},
        //{RunningEffectType.PLAY_EMOTE, typeof(PlayEmote)},
        //{RunningEffectType.CHARAC_SET_DMG_AIR, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_DMG_EARTH, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_DMG_WATER, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_DMG_FIRE, typeof(CharacSet)},
        //{RunningEffectType.HEAL_BOOST_PERCENT_FUNCTION_DMG_BONUS, typeof(HealBoostPercentFunctionDmgBonus)},
        //{RunningEffectType.HP_BOOST_FUNCTION_DMG_BONUS, typeof(HPBoostFunctionDmgBonus)},
        //{RunningEffectType.CHARAC_SET_DMG_IN_PERCENT, typeof(CharacSet)},
        //{RunningEffectType.SET_OUT_FIGHT_HP_REGEN, typeof(SetOutFightHpRegen)},
        //{RunningEffectType.CHARAC_SET_RES_AIR, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_RES_EARTH, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_RES_WATER, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_RES_FIRE, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_RES_IN_PERCENT, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_HEAL_IN_PERCENT, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_HP, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_AP_DBUFF_POWER, typeof(CharacSet)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_MAX_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_MAX_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_MAX_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_MAX_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_MAX_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_CURRENT_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_CURRENT_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_CURRENT_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_CURRENT_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_CURRENT_CASTER, typeof(HPLoss)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST, typeof(HPLoss)},
        //{RunningEffectType.RANDOM_HP_AIR_LOSS, typeof(RandomHPLoss)},
        //{RunningEffectType.RANDOM_HP_EARTH_LOSS, typeof(RandomHPLoss)},
        //{RunningEffectType.RANDOM_HP_FIRE_LOSS, typeof(RandomHPLoss)},
        //{RunningEffectType.RANDOM_HP_WATER_LOSS, typeof(RandomHPLoss)},
        //{RunningEffectType.HP_LOSS_FUNCTION_PA_PM, typeof(HpLossFunctionPaPm)},
        //{RunningEffectType.ADD_SPELL_TO_INVENTORY, typeof(AddSpellToInventory)},
        //{RunningEffectType.INIT_LOSS_FUNCTION_PA_PM, typeof(CharacLossFunctionPaPm)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_FIRE_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_EARTH_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_WATER_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST, typeof(HPLoss)},
        {RunningEffectType.HP_AIR_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST, typeof(HPLoss)},
        //{RunningEffectType.HP_LOSS_FUNCTION_PA_PM_WITHOUT_CONSUME_EARTH, typeof(HpLossFctPaPmWithoutConsume)},
        //{RunningEffectType.HP_LOSS_FUNCTION_PA_PM_WITHOUT_CONSUME_FIRE, typeof(HpLossFctPaPmWithoutConsume)},
        //{RunningEffectType.RESOURCEFULNESS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CRAFT_QUICKNESS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.QUICK_LEARNER_HARVEST_GAIN, typeof(CharacGain)},
        //{RunningEffectType.QUICK_LEARNER_CRAFT_GAIN, typeof(CharacGain)},
        //{RunningEffectType.GREEN_THUMBS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.ECOSYSTEM_SKILL_MODIFICATION, typeof(EcosystemSkillModification)},
        //{RunningEffectType.CRAFT_SKILL_MODIFICATION, typeof(CraftSkillModification)},
        //{RunningEffectType.RESOURCEFULNESS_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.GET_TITLE, typeof(GetPlayerTitle)},
        //{RunningEffectType.HP_LOSS_AND_PUPPET_HEAL, typeof(HpLossAndPuppetHeal)},
        //{RunningEffectType.LINK_CASTER_AND_TARGET, typeof(LinkCasterAndTarget)},
        //{RunningEffectType.CHANGE_SPELL_TARGET_CELL, typeof(ChangeSpellTargetCell)},
        //{RunningEffectType.SET_CHANGE_SPELL_TARGET_CELL_AREA, typeof(SetChangeSpellTargetCellArea)},
        //{RunningEffectType.ENUTROF_DEPOSIT_PLACEMENT, typeof(EnutrofDepositPlacement)},
        //{RunningEffectType.REMOVE_OWN_DEPOSIT, typeof(RemoveOwnDeposit)},
        //{RunningEffectType.AP_AS_MP, typeof(ApAsMp)},
        //{RunningEffectType.FAKE_KO, typeof(FakeKo)},
        //{RunningEffectType.HP_LOSS_NORMAL_DISTRIB_EARTH, typeof(HpLossNormalDistrib)},
        //{RunningEffectType.CHARAC_GAIN_BASED_ON_OTHER_CHARAC_VALUE, typeof(CharacGainBasedOnOtherCharacValue)},
        //{RunningEffectType.SET_LOOT_EFFECT_AREA, typeof(SetLootEffectArea)},
        //{RunningEffectType.DROP_FROM_LOOT_AREA, typeof(DropFromLootArea)},
        //{RunningEffectType.HP_LOSS_FROM_LOOT_AREA, typeof(HpLossFromLootArea)},
        //{RunningEffectType.COLLECT_FOR_CONTROLLER, typeof(CollectForController)},
        //{RunningEffectType.REPLACE_AREA_BY_ANOTHER, typeof(ReplaceAreaByAnother)},
        //{RunningEffectType.HP_LOSS_FUNCTION_LOOT, typeof(HpLossFunctionLoot)},
        //{RunningEffectType.CHRAGE_BUFF, typeof(CharacBuff)},
        //{RunningEffectType.HP_LOSS_AFTER_MOVEMENT, typeof(HpLossAfterMovement)},
        //{RunningEffectType.DROP_FOR_ENUTROF_BLESSING, typeof(DropForEnutrofBlessing)},
        //{RunningEffectType.INSTANT_KO, typeof(InstantKO)},
        //{RunningEffectType.BLITZKRIEK_EFFECT, typeof(BlitzkriekEffect)},
        //{RunningEffectType.ELEMENT_SPELL_GAIN, typeof(ElementalSpellGain)},
        //{RunningEffectType.DOUBLE_OR_QUITS, typeof(DoubleOrQuits)},
        //{RunningEffectType.BOOST_VOODOOL_DMG, typeof(CharacGain)},
        //{RunningEffectType.VOODOOL_SPLIT_EFFECT, typeof(VoodoolSplitEffect)},
        //{RunningEffectType.VOODOOL_BOOST_EFFECT, typeof(VoodoolBoostEffect)},
        //{RunningEffectType.HP_GAIN_RANDOM_PERCENT_OF_VALUE, typeof(HpGainRandomPercentOfValue)},
        //{RunningEffectType.SUMMONING_MASTERY, typeof(CharacGain)},
        //{RunningEffectType.SUMMON_DOUBLE_FOR_BELLAPHONE, typeof(SummonDoubleForBellaphone)},
        //{RunningEffectType.BOMB_COOLDOWN_DECREASE, typeof(CharacLoss)},
        //{RunningEffectType.BOMB_COOLDOWN_BUFF, typeof(CharacBuff)},
        //{RunningEffectType.SET_BARREL, typeof(SetEffectArea)},
        //{RunningEffectType.REMOVE_AREA_USING_TARGET, typeof(RemoveAreaUsingTarget)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_STATE, typeof(RunningEffectGroupLevelFunctionState)},
        //{RunningEffectType.STATE_GENERIC_APPLICATION_BONUS, typeof(CharacGain)},
        //{RunningEffectType.STATE_RESISTANCE_BONUS, typeof(CharacGain)},
        //{RunningEffectType.HP_LOSS_THEN_HP_LOSS_FUNCTION_PREVIOUS_VALUE_EARTH, typeof(HpLossThenHpLossFunctionPreviousValue)},
        //{RunningEffectType.ARMOR_PLATE_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.FECA_GLYPH_CHARGE_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.HP_LOSS_FUNCTION_CHARAC, typeof(HpLossFunctionCharac)},
        //{RunningEffectType.INVERT_DMG_AND_RES, typeof(PropertyApply)},
        //{RunningEffectType.HP_LOSS_FUNCTION_TRIGGERING_VALUE, typeof(HpLossFunctionTriggeringValue)},
        //{RunningEffectType.APPLY_CANT_BE_PUSH_OR_PULLED, typeof(PropertyApply)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_WITH_AT_LEAST_NULL_EFFECT, typeof(RunningEffectGroupWithAtLeastNullEffect)},
        //{RunningEffectType.PM_TRANSFER_TO_TARGETS, typeof(CharacTransferToTargets)},
        //{RunningEffectType.TACKLE_TRANSFER_TO_TARGETS, typeof(CharacTransferToTargets)},
        //{RunningEffectType.DODGE_TRANSFER_TO_TARGETS, typeof(CharacTransferToTargets)},
        //{RunningEffectType.BRING_BACK_TO_OWNER_SYMBIOT, typeof(BringBackToControllerSymbiot)},
        //{RunningEffectType.CHANGE_LEVEL, typeof(ChangeLevel)},
        //{RunningEffectType.OSA_INIT_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.OSA_CC_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.OSA_DODGE_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.OSA_TACKLE_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.GROUP_SECOND_VALUE_FUNCTION_FIRST, typeof(RunningEffectGroupSecondValueFunctionFirst)},
        //{RunningEffectType.PERCEPTION_GAIN, typeof(CharacGain)},
        //{RunningEffectType.PERCEPTION_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.FINAL_DMG_GAIN_FUNCTION_STATE_LEVEL, typeof(CharacGainFunctionStateLevel)},
        //{RunningEffectType.OSA_DMG_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.OSA_AP_GAIN, typeof(CharacBuffForOsaFusion)},
        //{RunningEffectType.OSA_MP_GAIN, typeof(CharacBuffForOsaFusion)},
        //{RunningEffectType.WILLPOWER_GAIN, typeof(CharacGain)},
        //{RunningEffectType.WILLPOWER_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.OSA_RANGE_GAIN, typeof(CharacGainForOsaFusion)},
        //{RunningEffectType.BLOCK_GAIN, typeof(CharacGain)},
        //{RunningEffectType.BLOCK_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.HP_MIN_MODIFICATION, typeof(CharacMinModification)},
        //{RunningEffectType.MOVE_AWAY_FROM_CELL, typeof(MoveAwayFromCell)},
        //{RunningEffectType.VIRTUAL_ARMOR_BONUS_GAIN, typeof(CharacGain)},
        //{RunningEffectType.AREA_HP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.EFFECT_VALUE_FUNCTION_FECA_ARMOR, typeof(EffectValueFunctionCasterCharac)},
        //{RunningEffectType.EFFECT_VALUE_FUNCTION_GLYPH_CHARGE, typeof(EffectValueFunctionCasterCharac)},
        //{RunningEffectType.RES_AP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RES_MP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_PROBA_FUNCTION_PA_PM_PW, typeof(RunningEffectGroupProbabilityFunctionPaPmPw)},
        //{RunningEffectType.EFFECT_PROBA_FUNCTION_GLYPH_CHARGE, typeof(EffectProbaFunctionCasterCharac)},
        //{RunningEffectType.EFFECT_PROBA_FUNCTION_ARMOR_PLATE, typeof(EffectProbaFunctionCasterCharac)},
        //{RunningEffectType.MODIFY_SUB_EFFECT_BY_CHRAGE, typeof(ModifySubEffectValueByCasterCharac)},
        //{RunningEffectType.MODIFY_SUB_EFFECT_BY_TARGET_PLATE, typeof(ModifySubEffectValueByTargetCharac)},
        //{RunningEffectType.RANDOM_IN_AREA_BY_AREA_HP, typeof(RunningEffectGroupEffectRandomInAreaByAreaHp)},
        //{RunningEffectType.APPLY_STATE_PERCENT_FUNCTION_AREA_HP, typeof(ApplyStatePercentFunctionAreaHp)},
        //{RunningEffectType.DMG_WATER_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.DMG_AIR_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.DMG_EARTH_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.DMG_FIRE_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_PROBA_FUNCTION_STATE_LEVEL, typeof(RunningEffectGroupProbabilityFunctionStateLevel)},
        //{RunningEffectType.MODIFY_SUB_EFFECT_BY_ARMOR_PLATE, typeof(ModifySubEffectValueByCasterCharac)},
        //{RunningEffectType.REG_EXECUTION_COUNT_FUNCTION_AREA_HP, typeof(REGExecutionCountFunctionCharac)},
        //{RunningEffectType.AREA_HP_BUFF, typeof(CharacBuff)},
        //{RunningEffectType.MODIFY_DMG_IN_PERCENT_FUNTION_PROSPECTION, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.REPLACE_AREA_BY_ANOTHER_USING_TARGET, typeof(ReplaceAreaByAnotherUsingTarget)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_SPELL_COST, typeof(RunningEffectGroupLevelFunctionTriggeringSpell)},
        //{RunningEffectType.REMOVE_AREA_USING_TARGET_CELL, typeof(RemoveArea)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_ACTION_COST, typeof(RunningEffectGroupLevelFunctionTriggeringActionCost)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_CHARACTERISTIC, typeof(RunningEffectGroupLevelFunctionCharacteristic)},
        //{RunningEffectType.BOMB_COOLDOWN_LOSS_FUNCTION_PA_PM, typeof(CharacLossFunctionPaPm)},
        //{RunningEffectType.EXECUTE_TRIGGER_IN_EFFECT_ZONE, typeof(ExecuteTriggeringEffectInEffectZone)},
        //{RunningEffectType.MODIFY_DMG_IN_PERCENT_FUNCTION_INITIATIVE, typeof(CharacModifiedByAnother)},
        {RunningEffectType.HP_STASIS_LOSS, typeof(HPLoss)},
        //{RunningEffectType.DMG_STASIS_GAIN_PERCENT, typeof(CharacGain)},
        //{RunningEffectType.ROLLBACK_TRIGGERING_SPELL_AP_COST, typeof(CharacGainFunctionTriggeringSpellCost)},
        //{RunningEffectType.ROLLBACK_TRIGGERING_SPELL_MP_COST, typeof(CharacGainFunctionTriggeringSpellCost)},
        //{RunningEffectType.ROLLBACK_TRIGGERING_SPELL_WP_COST, typeof(CharacGainFunctionTriggeringSpellCost)},
        //{RunningEffectType.HP_LOSS_PERCENT_OF_VALUE, typeof(HpLossPercentOfValue)},
        //{RunningEffectType.EXECUTE_ACTION_COST, typeof(ExecuteActionCost)},
        //{RunningEffectType.CHARAC_SET_AREA_HP, typeof(CharacSet)},
        //{RunningEffectType.AREA_HP_GAIN, typeof(CharacGain)},
        //{RunningEffectType.INIT_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.RES_STASIS_LOSS_PERCENT, typeof(CharacLoss)},
        //{RunningEffectType.CHARAC_BUFF_BASED_ON_OTHER_CHARAC_VALUE, typeof(CharacBuffBasedOnOtherCharacValue)},
        //{RunningEffectType.CHARAC_SET_AP, typeof(CharacSet)},
        //{RunningEffectType.CHARAC_SET_INIT, typeof(CharacSet)},
        //{RunningEffectType.REPLACE_TARGET_BY_OWNER, typeof(ReplaceTriggeringEffectTargetByOwner)},
        //{RunningEffectType.DECURSE_LINKED_TO_CASTER, typeof(DecurseLinkedToCaster)},
        //{RunningEffectType.CHANGE_PLAYER_SPELLS_BY_MONSTER_ONES, typeof(ChangePlayerSpellsByMonsterOnes)},
        //{RunningEffectType.EXCLUDE_FROM_FIGHT, typeof(ExcludeFromFight)},
        //{RunningEffectType.REMOVE_ALL_AREAS_WITH_ID, typeof(RemoveAllAreasWithId)},
        //{RunningEffectType.SPAWN_MONSTER, typeof(SpawnMonsterForArcadeDungeon)},
        //{RunningEffectType.REMOVE_FROM_FIGHT_MAP, typeof(RemoveFromFightMap)},
        //{RunningEffectType.REG_EXECUTION_COUNT_FUNCTION_TRIGGERING_ACTION_COST, typeof(REGExecutionCountFunctionTriggeringActionCost)},
        //{RunningEffectType.HP_LOSS_STASIS_EXPONENTIAL_GROWTH, typeof(HpLossExponentialGrowth)},
        //{RunningEffectType.HP_LOSS_FIRE_EXPONENTIAL_GROWTH, typeof(HpLossExponentialGrowth)},
        //{RunningEffectType.HP_LOSS_EARTH_EXPONENTIAL_GROWTH, typeof(HpLossExponentialGrowth)},
        //{RunningEffectType.HP_LOSS_AIR_EXPONENTIAL_GROWTH, typeof(HpLossExponentialGrowth)},
        //{RunningEffectType.HP_LOSS_WATER_EXPONENTIAL_GROWTH, typeof(HpLossExponentialGrowth)},
        //{RunningEffectType.RES_WATER_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.RES_AIR_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.RES_EARTH_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.RES_FIRE_MODIFIED_BY_ARMOR_PLATE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.SET_CHRAGE_TO_DMG_RATIO, typeof(SetChrageToDmgRatio)},
        //{RunningEffectType.REG_EXECUTION_COUNT_FIXED, typeof(REGExecutionCountFixed)},
        //{RunningEffectType.SET_AP, typeof(SetCharac)},
        //{RunningEffectType.SET_MP, typeof(SetCharac)},
        //{RunningEffectType.SET_WP, typeof(SetCharac)},
        //{RunningEffectType.DEBUFF_FUMBLE_RATE, typeof(CharacDebuff)},
        //{RunningEffectType.SET_MICROBOT_RAILS_MAX_DISTANCE, typeof(SetCharac)},
        //{RunningEffectType.VIRTUAL_HP_BOOST_IN_PERCENT_FUNCTION_ALLIES_COUNT, typeof(CharacBoostInPercentFunctionAlliesCount)},
        //{RunningEffectType.VIRTUAL_HP_BOOST_IN_PERCENT, typeof(CharacBoostInPercentFunctionCaster)},
        //{RunningEffectType.SET_VIRTUAL_HP_FROM_HP, typeof(SetVirtualHpFromHp)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_MAX_WITH_VIRTUAL, typeof(HPLoss)},
        {RunningEffectType.HP_LOSS_IN_PERCENT_MAX_CASTER_WITH_VIRTUAL, typeof(HPLoss)},
        //{RunningEffectType.HP_LOSS_FIRE_FUNCTION_FIGHTER_LEVEL, typeof(HpLossFunctionFighterLevel)},
        //{RunningEffectType.HP_LOSS_EARTH_FUNCTION_FIGHTER_LEVEL, typeof(HpLossFunctionFighterLevel)},
        //{RunningEffectType.HP_LOSS_WATER_FUNCTION_FIGHTER_LEVEL, typeof(HpLossFunctionFighterLevel)},
        //{RunningEffectType.HP_LOSS_AIR_FUNCTION_FIGHTER_LEVEL, typeof(HpLossFunctionFighterLevel)},
        //{RunningEffectType.HP_LOSS_STASIS_FUNCTION_FIGHTER_LEVEL, typeof(HpLossFunctionFighterLevel)},
        //{RunningEffectType.ADD_SPELL_TO_TEMPORARY_SPELL_INVENTORY, typeof(AddSpellToTemporaryInventory)},
        //{RunningEffectType.PLANTATION_BONUS_PLANT, typeof(EcosystemSkillModification)},
        //{RunningEffectType.PLANTATION_BONUS_TREE, typeof(EcosystemSkillModification)},
        //{RunningEffectType.PLANTATION_BONUS_CULTIVATION, typeof(EcosystemSkillModification)},
        //{RunningEffectType.PLANTATION_BONUS_MOB, typeof(EcosystemSkillModification)},
        //{RunningEffectType.CRAFT_CRAFT_XP_BONUS, typeof(CraftSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_PLANT, typeof(EcosystemSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_TREE, typeof(EcosystemSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_CULTIVATION, typeof(EcosystemSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_MOB, typeof(EcosystemSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_MINERAL, typeof(EcosystemSkillModification)},
        //{RunningEffectType.COLLECT_BONUS_FISH, typeof(EcosystemSkillModification)},
        //{RunningEffectType.CRAFT_QUICKNESS_BONUS, typeof(CraftSkillModification)},
        //{RunningEffectType.PLANTATION_BONUS_TREASURE, typeof(EcosystemSkillModification)},
        //{RunningEffectType.ALL_ELEMENTAL_SPELL_GAIN, typeof(AllElementalSpellGain)},
        //{RunningEffectType.PASSIVE_SPELL_GAIN, typeof(PassiveSpellGain)},
        //{RunningEffectType.ACTIVE_SUPPORT_SPELL_GAIN, typeof(ActiveSupportSpellGain)},
        //{RunningEffectType.REMOVE_PASSIVE_SPELLS, typeof(RemoveEffectFromContainerType)},
        //{RunningEffectType.AP_SET_TO_MAX, typeof(SetCharacToMax)},
        //{RunningEffectType.SET_VITUAL_HP, typeof(SetCharac)},
        //{RunningEffectType.VIRTUAL_HP_SET_TO_MAX, typeof(SetCharacToMax)},
        //{RunningEffectType.UPDATE_HP_MAX_PERCENT_MODIFIER, typeof(UpdateCharacMaxPercentModifier)},
        //{RunningEffectType.ADD_BONUS_LOOT, typeof(AddBonusLoot)},
        //{RunningEffectType.CRITICAL_RES_GAIN, typeof(CharacGain)},
        //{RunningEffectType.UPDATE_VIRTUAL_HP_MAX_PERCENT_MODIFIER, typeof(UpdateCharacMaxPercentModifier)},
        //{RunningEffectType.HP_GAIN_FOR_UNDEAD, typeof(HPGainForUndead)},
        //{RunningEffectType.KO_TIME_BEFORE_DEATH_BUFF, typeof(CharacBuff)},
        {RunningEffectType.TELEPORT_CASTER_BEHIND_TARGET, typeof(TeleportBehindTarget)},
        //{RunningEffectType.CHANGE_SPELL_TARGET_CELL_BY_CASTER_CELL, typeof(ChangeSpellTargetCellByCasterCell)},
        //{RunningEffectType.SUMMON_DOUBLE_FOR_ICE_STATUE, typeof(SummonDoubleForIceStatue)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_SPELL, typeof(RunningEffectGroupLevelFunctionSpell)},
        //{RunningEffectType.OSA_INVOCATION_KNOWLEDGE_GAIN, typeof(CharacGain)},
        //{RunningEffectType.VIRTUAL_ARMOR_FLAT, typeof(VirtualArmorWithElement)},
        //{RunningEffectType.DMG_WATER_PERCENT_GAIN_FCT_CASTER_DMG_EARTH_PERCENT, typeof(CharacteristicType)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_CHARACTER_LEVEL, typeof(RunningEffectGroupLevelFunctionCharacterLevel)},
        //{RunningEffectType.CHANGE_TRIGERRING_EFFECT_TARGET, typeof(ChangeTriggeringEffectTarget)},
        //{RunningEffectType.COPY_CHARAC_AT_APPLICATION_VALUE, typeof(CopyCharacAtApplicationValue)},
        //{RunningEffectType.SUMMON_ZOBAL_DOUBLE, typeof(SummonZobalDouble)},
        //{RunningEffectType.KO_TIME_BEFORE_DEATH_MIN_MODIFICATION, typeof(CharacMinModification)},
        //{RunningEffectType.MODIFY_DMG_IN_PERCENT_FUNCTION_DODGE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.APPLY_STATE_CAPED_BY_ANOTHER_STATE, typeof(ApplyStateLevelCapedByAnotherState)},
        //{RunningEffectType.REG_SUB_EFFECT_VALUE_FUNCTION_CASTER_AP, typeof(CharacteristicType)},
        //{RunningEffectType.REG_SUB_EFFECT_VALUE_FUNCTION_CASTER_MP, typeof(CharacteristicType)},
        //{RunningEffectType.SET_EFFECT_AREA_FOR_ORIGINAL_CONTROLLER, typeof(SetEffectAreaForOriginalController)},
        //{RunningEffectType.MODIFY_HEAL_BONUS_IN_PERCENT_FUNCTION_DODGE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.ARMOR_GAIN, typeof(CharacGain)},
        //{RunningEffectType.ARMOR_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.ARMOR_ELEMENTAL_GAIN, typeof(ElementalCharacGain)},
        //{RunningEffectType.REDUCE_ZONE_EFFECT, typeof(ReduceZoneEffect)},
        //{RunningEffectType.COPY_CHARAC_IN_REAL_TIME, typeof(CopyCharacInRealTime)},
        //{RunningEffectType.BEST_ELEMENT_HP_LOSS, typeof(BestElementHpLoss)},
        //{RunningEffectType.BEST_ELEMENT_HP_GAIN, typeof(BestElementHpGain)},
        //{RunningEffectType.BEST_ELEMENT_HP_GAIN_FUNCTION_PA_PM, typeof(BestElementHpGainFunctionPaPm)},
        //{RunningEffectType.SPECIFIC_FOR_ARMOR_DAMAGE_REBOUND, typeof(SpecificForArmorDamageRebound)},
        //{RunningEffectType.PVP_BUFF_GAIN, typeof(PvPBuffGain)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_VALUE, typeof(RunningEffectGroupLevelFunctionTriggeringValue)},
        //{RunningEffectType.REMOVE_BLOCKING_AREA_USING_TARGET, typeof(RemoveBlockingAreaUsingTarget)},
        //{RunningEffectType.CRAFT_ECOSYSTEM_XP_BONUS, typeof(CraftSkillModification)},
        //{RunningEffectType.CRAFT_XP_BONUS, typeof(CraftXpBoost)},
        //{RunningEffectType.STATE_DECURSE_FOR_HYPERACTION, typeof(StateDecurseForHyperaction)},
        //{RunningEffectType.HP_GAIN_FUNCTION_CASTER_EARTH, typeof(HPGainForTargetBasedOnCaster)},
        //{RunningEffectType.HP_GAIN_FUNCTION_CASTER_AIR, typeof(HPGainForTargetBasedOnCaster)},
        //{RunningEffectType.HP_GAIN_FUNCTION_CASTER_WATER, typeof(HPGainForTargetBasedOnCaster)},
        //{RunningEffectType.HP_GAIN_FUNCTION_CASTER_FIRE, typeof(HPGainForTargetBasedOnCaster)},
        //{RunningEffectType.HP_GAIN_FUNCTION_CASTER_PHYSICAL, typeof(HPGainForTargetBasedOnCaster)},
        //{RunningEffectType.SET_TEAM_ID, typeof(SetTeamId)},
        //{RunningEffectType.REMOVE_EQUIPMENT_EFFECTS, typeof(RemoveEffectFromContainerType)},
        //{RunningEffectType.REMOVE_SET_EFFECTS, typeof(RemoveEffectFromContainerType)},
        //{RunningEffectType.SET_STEAMER_BLOCK, typeof(SetSteamerBlock)},
        //{RunningEffectType.STEAMER_BLOCK_PASSIVE_RESIST, typeof(SimpleValueEffect)},
        //{RunningEffectType.STEAMER_BLOCK_DAMAGE_REDIRECTION, typeof(SteamerBlockDamageRedirection)},
        //{RunningEffectType.WEAKEST_RESIST_GAIN, typeof(WeakestResistGain)},
        //{RunningEffectType.STEAMER_DAMAGE_REDIRECTION, typeof(SteamerDamageRedirection)},
        //{RunningEffectType.ADD_CHARAC_VALUE_TO_ANOTHER_IN_REAL_TIME, typeof(AddCharacValueToAnotherInRealTime)},
        //{RunningEffectType.CHARAC_SET_LEADERSHIP, typeof(CharacSet)},
        //{RunningEffectType.SET_RESISTANCE_TARGET, typeof(SetResistanceTarget)},
        //{RunningEffectType.REG_EXECUTION_COUNT_FUNCTION_ALLIES_COUNT, typeof(REGExecutionCountFunctionAlliesCount)},
        //{RunningEffectType.BARRIER_ELEMENTAL_GAIN, typeof(ElementalCharacGain)},
        //{RunningEffectType.UPDATE_TACKLE_HP_MAX_PERCENT_MODIFIER, typeof(UpdateCharacMaxPercentModifier)},
        //{RunningEffectType.CHANGE_AREA_POSITION, typeof(ChangeAreaPosition)},
        //{RunningEffectType.MODIFY_RES_IN_PERCENT_FUNCTION_TACKLE, typeof(CharacModifiedByAnother)},
        //{RunningEffectType.ADD_TO_AI_PRIORITY_TARGETS, typeof(AddToAiIgnoreResistancesTargets)},
        //{RunningEffectType.RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TOTAL_HP, typeof(RunningEffectGroupLevelFunctionTotalHp)},
        //{RunningEffectType.DIVIDE_HP_LOSS_UNLESS_THRESHOLD, typeof(DividedHpLossUnlessThreshold)},
        //{RunningEffectType.SWITCH_CHARAC_VALUES, typeof(SwitchCharacValues)},
        //{RunningEffectType.AOE_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.SINGLE_TARGET_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.MELEE_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.RANGED_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.NON_CRIT_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.BERSERK_DMG_GAIN, typeof(CharacGain)},
        //{RunningEffectType.CRITICAL_BONUS_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.SINGLE_TARGET_DMG_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.AOE_DMG_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.MELEE_DMG_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RANGED_DMG_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.BERSERK_DMG_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.CRITICAL_RES_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.RES_BACKSTAB_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.LEADERSHIP_LOSS, typeof(CharacLoss)},
        //{RunningEffectType.SPELL_WITH_PROPERTY_AP_COST_REDUCTION, typeof(SpellsWithPropertyApCostReduction)},
        //{RunningEffectType.SPELL_WITH_PROPERTY_RANGE_GAIN, typeof(SpellsWithPropertyRangeGain)},
        //{RunningEffectType.TACKLE_ACTION_COST, typeof(TackleActionCost)},
        //{RunningEffectType.VARIABLE_ELEMENTS_DAMAGE_GAIN, typeof(VariableElementDamageGain)},
        //{RunningEffectType.VARIABLE_ELEMENTS_RES_GAIN, typeof(VariableElementResistanceGain)},
        //{RunningEffectType.ADD_CHARAC_VALUE_TO_ANOTHER_IN_REAL_TIME_WITH_THRESHOLD, typeof(AddCharacValueToAnotherInRealTimeWithThreshold)},
        //{RunningEffectType.VIRTUAL_HP_BOOST, typeof(CharacBuff)},
        //{RunningEffectType.REVERSI_CHECK_FOR_REVERSABLE, typeof(ReversiCheckForReversable)},
    };
}

    public enum RunningEffectType
{
    VARIABLE_EFFECT = -1,
    HP_LOSS = 1,
    HP_FIRE_LOSS = 2,
    HP_EARTH_LOSS = 3,
    HP_WATER_LOSS = 4,
    HP_AIR_LOSS = 5,
    HP_LOSS_WITH_KAMAS_WATER = 6,
    HP_LEECH = 11,
    HP_LEECH_FIRE = 12,
    HP_LEECH_EARTH = 13,
    HP_LEECH_WATER = 14,
    HP_LEECH_AIR = 15,
    SET_HP = 16,
    HP_GAIN_WITH_FEEDBACK = 17,
    HP_BOOST = 20,
    HP_DEBOOST = 21,
    HP_LOSS_ACCUMULATION = 23,
    COPY_CHARAC_MAX = 24,
    HP_GAIN = 25,
    HEAL_GAIN = 26,
    HEAL_LOSS = 27,
    DEATH = 28,
    HP_GAIN_PERCENT_OF_VALUE = 29,
    ACTION_COST = 30,
    AP_BOOST = 31,
    AP_DEBOOST = 32,
    AP_GAIN = 33,
    AP_LEECH = 35,
    AP_GIFT = 36,
    AP_LOSS = 37,
    RES_AP_GAIN = 38,
    CHARAC_GAIN = 39,
    CHARAC_LOSS = 40,
    MP_BOOST = 41,
    MP_DEBOOST = 42,
    MP_GAIN = 43,
    MP_LOSS = 44,
    MP_LEECH = 45,
    RES_MP_GAIN = 46,
    SPELL_BOOST_LEVEL = 47,
    HP_LOSS_WITH_REBOUND = 50,
    HP_EARTH_LOSS_WITH_REBOUND = 51,
    HP_FIRE_LOSS_WITH_REBOUND = 52,
    HP_WATER_LOSS_WITH_REBOUND = 53,
    HP_AIR_LOSS_WITH_REBOUND = 54,
    HP_EXCHANGE = 59,
    HP_GAIN_WITH_REBOUND_WATER = 60,
    CHARAC_STEAL_WITH_LOSS = 61,
    AP_LEECH_IN_PERCENT = 62,
    WP_LEECH_IN_PERCENT = 63,
    DMG_LEECH_IN_PERCENT = 64,
    RES_LEECH_IN_PERCENT = 65,
    MP_LEECH_IN_PERCENT = 66,
    HP_GAIN_WITH_REBOUND_AIR = 67,
    RES_HEAL_GAIN = 70,
    RES_BACK_GAIN = 71,
    RES_HEAL_LOSS = 72,
    WP_LEECH = 73,
    INIT_LEECH = 74,
    RES_GAIN_IN_PERCENT = 80,
    RES_FIRE_GAIN_PERCENT = 82,
    RES_WATER_GAIN_PERCENT = 83,
    RES_EARTH_GAIN_PERCENT = 84,
    RES_AIR_GAIN_PERCENT = 85,
    RES_LOSS_IN_PERCENT = 90,
    RES_EARTH_LOSS_PERCENT = 92,
    RES_FIRE_LOSS_PERCENT = 93,
    RES_WATER_LOSS_PERCENT = 94,
    RES_AIR_LOSS_PERCENT = 95,
    DMG_GAIN_IN_PERCENT = 120,
    DMG_FIRE_GAIN_PERCENT = 122,
    DMG_EARTH_GAIN_PERCENT = 123,
    DMG_WATER_GAIN_PERCENT = 124,
    DMG_AIR_GAIN_PERCENT = 125,
    FINAL_DMG_IN_PERCENT = 126,
    FINAL_RES_IN_PERCENT = 127,
    FINAL_RES_IN_PERCENT_LOSS = 128,
    FINAL_DMG_IN_PERCENT_LOSS = 129,
    DMG_LOSS_IN_PERCENT = 130,
    DMG_FIRE_LOSS_PERCENT = 132,
    DMG_EARTH_LOSS_PERCENT = 133,
    DMG_WATER_LOSS_PERCENT = 134,
    DMG_AIR_LOSS_PERCENT = 135,
    PUNISHMENT = 136,
    DAMAGES_REBOUND_IN_PERCENT = 140,
    DAMAGES_ABSORB_IN_PERCENT = 141,
    LIFE_STOLEN_BONUS_GAIN = 148,
    CRITICAL_BONUS_GAIN = 149,
    CC_GAIN = 150,
    EC_GAIN = 151,
    AGILITY_GAIN = 152,
    AGILITY_LOSS = 153,
    STRENGTH_GAIN = 154,
    STRENGTH_LOSS = 155,
    INTELLIGENCE_GAIN = 156,
    INTELLIGENCE_LOSS = 157,
    LUCK_GAIN = 158,
    LUCK_LOSS = 159,
    RANGE_GAIN = 160,
    RANGE_LOSS = 161,
    PROSPECTION_GAIN = 162,
    PROSPECTION_LOSS = 163,
    WISDOM_GAIN = 166,
    WISDOM_LOSS = 167,
    FEROCITY_LOSS = 168,
    FUMBLE_RATE_LOSS = 169,
    INIT_GAIN = 171,
    INIT_LOSS = 172,
    TACKLE_GAIN = 173,
    TACKLE_LOSS = 174,
    DODGE_GAIN = 175,
    DODGE_LOSS = 176,
    BACKSTAB_BONUS_GAIN = 180,
    BACKSTAB_BONUS_LOSS = 181,
    MECHANISM_MASTERY = 182,
    BONUS_TRAP = 183,
    BONUS_SUMMON = 184,
    WP_BOOST = 191,
    WP_DEBOOST = 192,
    WP_GAIN = 193,
    WP_LOSS = 194,
    WP_STEAL = 195,
    RAISE = 196,
    VITALITY_GAIN = 197,
    VITALITY_LOSS = 198,
    SKIP_TURN = 200,
    REDUCE_RANGE_TO_CAC = 201,
    ROOTED = 202,
    IMMUNE_TO_MP_LOSS = 203,
    INVISIBLE = 204,
    INVISIBLE_SUPERIOR = 205,
    FIGHT_FORBIDDEN = 206,
    CHANGE_CONTROLLER = 207,
    COWARD = 208,
    HASTE = 209,
    STABILIZED = 210,
    CANT_BE_ATTACKED = 211,
    CANT_TACKLE = 212,
    STATE_RESISTANCE = 213,
    NO_FIGHT_XP = 214,
    SET_MAX_AP_COS = 215,
    SET_EFFECT_AREA_GRIP = 216,
    REVEAL_INVISIBLE = 217,
    UNDEAD = 218,
    UNTARGETTABLE = 219,
    IA_DOUBLE_FOCUS = 220,
    STASIS_1 = 221,
    STASIS_2 = 222,
    STASIS_3 = 223,
    IA_MINIMIZE_FOCUS = 224,
    RAISE_OUT_OF_COMBAT = 225,
    GROGGY_1 = 226,
    GROGGY_2 = 227,
    GROGGY_3 = 228,
    CRIPPLED_1 = 229,
    CRIPPLED_2 = 230,
    CRIPPLED_3 = 231,
    LAME = 232,
    EQUIPMENT_KNOWLEDGE_GAIN = 234,
    AP_DEBUFF_POWER = 235,
    MP_DEBUFF_POWER = 236,
    EXTRA_TURN = 237,
    NO_DEATH = 238,
    STATE_APPLICATION_BONUS = 239,
    DONT_BLOCK_LOS = 240,
    ESCAPE_TACKLE = 241,
    CANT_TELEPORT = 242,
    HP_BOOST_IN_PERCENT_FUNCTION_ALLIES_COUNT = 249,
    HP_BOOST_IN_PERCENT = 250,
    HP_GAIN_AIR = 251,
    HP_GAIN_EARTH = 253,
    HP_GAIN_WATER = 258,
    HP_GAIN_FIRE = 259,
    WISDOM_BOOST = 260,
    HP_GAIN_AIR_FOR_CASTER_BASED_ON_TARGET = 261,
    HP_GAIN_EARTH_FOR_CASTER_BASED_ON_TARGET = 262,
    HP_GAIN_WATER_FOR_CASTER_BASED_ON_TARGET = 263,
    HP_GAIN_FIRE_FOR_CASTER_BASED_ON_TARGET = 264,
    HP_GAIN_PHYSICAL_FOR_CASTER_BASED_ON_TARGET = 265,
    INIT_GAIN_PERCENT_OF_VALUE = 270,
    INIT_LOSS_PERCENT_OF_VALUE = 271,
    MP_SET_TO_MAX = 272,
    PUSH = 300,
    PULL = 301,
    TELEPORT_CASTER = 302,
    ATTRACT_SIGHT = 303,
    STATE_APPLY = 304,
    GET_CLOSER = 305,
    PULL_ON_CASTER_BACK = 306,
    SUMMON = 307,
    SET_TRAP = 308,
    SPELL_REBOUND = 309,
    RUNNING_STATE = 310,
    SET_CADRAN = 311,
    SET_HOUR = 312,
    SET_BEACON = 313,
    SET_AURA = 314,
    SET_GLYPH = 315,
    UNSET_AURAS = 316,
    SET_BOMB = 317,
    SEDUCE_MONSTER = 320,
    STATE_FORCE_UNAPPLY = 321,
    SUMMON_SRAM_DOUBLE = 322,
    BRING_BACK = 323,
    SUMMON_FROM_SYMBIOT = 324,
    SET_AI = 325,
    WEAPONATTACK = 326,
    AI_GIVE_ORDER = 327,
    AI_GIVE_ORDER_CELL = 328,
    RUNNING_EFFECT_GROUP = 330,
    REPELL = 331,
    UNSUMMON = 332,
    THROW = 333,
    CARRY = 334,
    UPDATE_MAX_SEDUCABLE_CREATURES = 337,
    SET_AURA_ON_TARGET = 338,
    SET_EFFECT_AREA = 339,
    TELEPORT_TARGET = 340,
    RANDOM_RUNNING_EFFECT_GROUP = 341,
    MAKE_FLEE = 342,
    APPLY_STATE_FUNCTION_PA_PM_PW = 343,
    SPELL_BREAK = 344,
    RUNNING_EFFECT_GROUP_RANDOM_TARGETS = 345,
    APPLY_DEATHTAG = 346,
    SUMMON_IMAGE = 347,
    SET_AREA_WITH_LEVEL_FUNCTION_SPELL = 348,
    EFFECT_RANDOM_IN_AREA = 349,
    APPLY_STATE_WITHOUT_NOTIFICATION = 350,
    STATE_DECURSE_WITHOUT_NOTIFICATION = 351,
    APPLY_STATE_FUNCTION_ACTION_COST = 352,
    APPLY_STATE_FOR_FECA_ARMOR = 353,
    REMOVE_FECA_ARMOR = 354,
    SET_FECA_GLYPH = 355,
    XELORS_DIAL_CHARGE_GAIN = 356,
    XELORS_DIAL_CHARGE_LOSS = 357,
    SET_AI_WITH_SPELLS_FOR_IA_SERVER = 358,
    NULL_EFFECT = 400,
    SPLIT_TRIGGER_EFFECT = 401,
    NULL_EFFECT_ON_CELL = 402,
    NULL_EFFECT_NOTIFIED_TO_AI = 403,
    HP_LOSS_IN_PERCENT_MAX = 411,
    HP_FIRE_LOSS_IN_PERCENT_MAX = 412,
    HP_EARTH_LOSS_IN_PERCENT_MAX = 413,
    HP_WATER_LOSS_IN_PERCENT_MAX = 414,
    HP_AIR_LOSS_IN_PERCENT_MAX = 415,
    HP_LOSS_IN_PERCENT_CURRENT = 416,
    HP_FIRE_LOSS_IN_PERCENT_CURRENT = 417,
    HP_EARTH_LOSS_IN_PERCENT_CURRENT = 418,
    HP_WATER_LOSS_IN_PERCENT_CURRENT = 419,
    HP_AIR_LOSS_IN_PERCENT_CURRENT = 420,
    DECURSE = 421,
    EXCHANGE_POSITION = 422,
    SPELL_ATTACK = 426,
    UPDATE_VALUE = 430,
    KAMA_STEAL = 431,
    PICK_UP_ITEM = 432,
    BOOST_SKILL_WITH_SPELL = 433,
    KAMA_SHIELD = 434,
    UPDATE_TARGET_WITH_CARRIER = 435,
    VIRTUAL_ARMOR = 436,
    REVEAL_INVISIBILITY = 438,
    POISON_AP = 440,
    POISON_MP = 441,
    POISON_WP = 442,
    UPDATE_CASTER_WITH_TARGET = 443,
    CONFUSED = 444,
    IMMUNE_TO_EFFECTS = 445,
    REMOVE_FIGHT_PROPERTY = 446,
    APPLY_FIGHT_PROPERTY = 447,
    POISON_TRIGERRING_VALUE = 448,
    APPLY_WORLD_PROPERTY = 449,
    PLAY_EMOTE = 550,
    CHARAC_SET_DMG_AIR = 560,
    CHARAC_SET_DMG_EARTH = 561,
    CHARAC_SET_DMG_WATER = 562,
    CHARAC_SET_DMG_FIRE = 563,
    HEAL_BOOST_PERCENT_FUNCTION_DMG_BONUS = 564,
    HP_BOOST_FUNCTION_DMG_BONUS = 565,
    CHARAC_SET_DMG_IN_PERCENT = 566,
    SET_OUT_FIGHT_HP_REGEN = 567,
    CHARAC_SET_RES_AIR = 568,
    CHARAC_SET_RES_EARTH = 569,
    CHARAC_SET_RES_WATER = 570,
    CHARAC_SET_RES_FIRE = 571,
    CHARAC_SET_RES_IN_PERCENT = 572,
    CHARAC_SET_HEAL_IN_PERCENT = 573,
    CHARAC_SET_HP = 574,
    CHARAC_SET_AP_DBUFF_POWER = 575,
    HP_LOSS_IN_PERCENT_MAX_CASTER = 620,
    HP_FIRE_LOSS_IN_PERCENT_MAX_CASTER = 621,
    HP_EARTH_LOSS_IN_PERCENT_MAX_CASTER = 622,
    HP_WATER_LOSS_IN_PERCENT_MAX_CASTER = 623,
    HP_AIR_LOSS_IN_PERCENT_MAX_CASTER = 624,
    HP_LOSS_IN_PERCENT_CURRENT_CASTER = 625,
    HP_FIRE_LOSS_IN_PERCENT_CURRENT_CASTER = 626,
    HP_EARTH_LOSS_IN_PERCENT_CURRENT_CASTER = 627,
    HP_WATER_LOSS_IN_PERCENT_CURRENT_CASTER = 628,
    HP_AIR_LOSS_IN_PERCENT_CURRENT_CASTER = 629,
    HP_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST = 630,
    HP_FIRE_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST = 631,
    HP_EARTH_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST = 632,
    HP_WATER_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST = 633,
    HP_AIR_LOSS_IN_PERCENT_CURRENT_CASTER_LIFE_LOST = 634,
    RANDOM_HP_AIR_LOSS = 635,
    RANDOM_HP_EARTH_LOSS = 636,
    RANDOM_HP_FIRE_LOSS = 637,
    RANDOM_HP_WATER_LOSS = 638,
    HP_LOSS_FUNCTION_PA_PM = 639,
    ADD_SPELL_TO_INVENTORY = 640,
    INIT_LOSS_FUNCTION_PA_PM = 641,
    HP_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST = 642,
    HP_FIRE_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST = 643,
    HP_EARTH_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST = 644,
    HP_WATER_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST = 645,
    HP_AIR_LOSS_IN_PERCENT_CURRENT_TARGET_LIFE_LOST = 646,
    HP_LOSS_FUNCTION_PA_PM_WITHOUT_CONSUME_EARTH = 647,
    HP_LOSS_FUNCTION_PA_PM_WITHOUT_CONSUME_FIRE = 648,
    RESOURCEFULNESS_GAIN = 700,
    CRAFT_QUICKNESS_GAIN = 702,
    QUICK_LEARNER_HARVEST_GAIN = 705,
    QUICK_LEARNER_CRAFT_GAIN = 706,
    GREEN_THUMBS_GAIN = 707,
    ECOSYSTEM_SKILL_MODIFICATION = 708,
    CRAFT_SKILL_MODIFICATION = 709,
    RESOURCEFULNESS_LOSS = 710,
    GET_TITLE = 800,
    HP_LOSS_AND_PUPPET_HEAL = 801,
    LINK_CASTER_AND_TARGET = 802,
    CHANGE_SPELL_TARGET_CELL = 803,
    SET_CHANGE_SPELL_TARGET_CELL_AREA = 804,
    ENUTROF_DEPOSIT_PLACEMENT = 805,
    REMOVE_OWN_DEPOSIT = 807,
    AP_AS_MP = 808,
    FAKE_KO = 809,
    HP_LOSS_NORMAL_DISTRIB_EARTH = 810,
    CHARAC_GAIN_BASED_ON_OTHER_CHARAC_VALUE = 812,
    SET_LOOT_EFFECT_AREA = 813,
    DROP_FROM_LOOT_AREA = 814,
    HP_LOSS_FROM_LOOT_AREA = 815,
    COLLECT_FOR_CONTROLLER = 816,
    REPLACE_AREA_BY_ANOTHER = 817,
    HP_LOSS_FUNCTION_LOOT = 818,
    CHRAGE_BUFF = 819,
    HP_LOSS_AFTER_MOVEMENT = 825,
    DROP_FOR_ENUTROF_BLESSING = 828,
    INSTANT_KO = 830,
    BLITZKRIEK_EFFECT = 831,
    ELEMENT_SPELL_GAIN = 832,
    DOUBLE_OR_QUITS = 833,
    BOOST_VOODOOL_DMG = 834,
    VOODOOL_SPLIT_EFFECT = 835,
    VOODOOL_BOOST_EFFECT = 836,
    HP_GAIN_RANDOM_PERCENT_OF_VALUE = 837,
    SUMMONING_MASTERY = 838,
    SUMMON_DOUBLE_FOR_BELLAPHONE = 839,
    BOMB_COOLDOWN_DECREASE = 840,
    BOMB_COOLDOWN_BUFF = 841,
    SET_BARREL = 842,
    REMOVE_AREA_USING_TARGET = 843,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_STATE = 844,
    STATE_GENERIC_APPLICATION_BONUS = 845,
    STATE_RESISTANCE_BONUS = 846,
    HP_LOSS_THEN_HP_LOSS_FUNCTION_PREVIOUS_VALUE_EARTH = 847,
    ARMOR_PLATE_BONUS_GAIN = 849,
    FECA_GLYPH_CHARGE_BONUS_GAIN = 850,
    HP_LOSS_FUNCTION_CHARAC = 851,
    INVERT_DMG_AND_RES = 852,
    HP_LOSS_FUNCTION_TRIGGERING_VALUE = 853,
    APPLY_CANT_BE_PUSH_OR_PULLED = 854,
    RUNNING_EFFECT_GROUP_WITH_AT_LEAST_NULL_EFFECT = 855,
    PM_TRANSFER_TO_TARGETS = 856,
    TACKLE_TRANSFER_TO_TARGETS = 857,
    DODGE_TRANSFER_TO_TARGETS = 858,
    BRING_BACK_TO_OWNER_SYMBIOT = 859,
    CHANGE_LEVEL = 860,
    OSA_INIT_GAIN = 861,
    OSA_CC_GAIN = 862,
    OSA_DODGE_GAIN = 863,
    OSA_TACKLE_GAIN = 864,
    GROUP_SECOND_VALUE_FUNCTION_FIRST = 865,
    PERCEPTION_GAIN = 866,
    PERCEPTION_LOSS = 867,
    FINAL_DMG_GAIN_FUNCTION_STATE_LEVEL = 868,
    OSA_DMG_GAIN = 869,
    OSA_AP_GAIN = 870,
    OSA_MP_GAIN = 871,
    WILLPOWER_GAIN = 872,
    WILLPOWER_LOSS = 873,
    OSA_RANGE_GAIN = 874,
    BLOCK_GAIN = 875,
    BLOCK_LOSS = 876,
    HP_MIN_MODIFICATION = 877,
    MOVE_AWAY_FROM_CELL = 878,
    VIRTUAL_ARMOR_BONUS_GAIN = 879,
    AREA_HP_LOSS = 880,
    EFFECT_VALUE_FUNCTION_FECA_ARMOR = 881,
    EFFECT_VALUE_FUNCTION_GLYPH_CHARGE = 882,
    RES_AP_LOSS = 884,
    RES_MP_LOSS = 885,
    RUNNING_EFFECT_GROUP_PROBA_FUNCTION_PA_PM_PW = 886,
    EFFECT_PROBA_FUNCTION_GLYPH_CHARGE = 887,
    EFFECT_PROBA_FUNCTION_ARMOR_PLATE = 892,
    MODIFY_SUB_EFFECT_BY_CHRAGE = 894,
    MODIFY_SUB_EFFECT_BY_TARGET_PLATE = 895,
    RANDOM_IN_AREA_BY_AREA_HP = 896,
    APPLY_STATE_PERCENT_FUNCTION_AREA_HP = 897,
    DMG_WATER_MODIFIED_BY_ARMOR_PLATE = 900,
    DMG_AIR_MODIFIED_BY_ARMOR_PLATE = 901,
    DMG_EARTH_MODIFIED_BY_ARMOR_PLATE = 902,
    DMG_FIRE_MODIFIED_BY_ARMOR_PLATE = 903,
    RUNNING_EFFECT_GROUP_PROBA_FUNCTION_STATE_LEVEL = 904,
    MODIFY_SUB_EFFECT_BY_ARMOR_PLATE = 905,
    REG_EXECUTION_COUNT_FUNCTION_AREA_HP = 906,
    AREA_HP_BUFF = 907,
    MODIFY_DMG_IN_PERCENT_FUNTION_PROSPECTION = 908,
    REPLACE_AREA_BY_ANOTHER_USING_TARGET = 909,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_SPELL_COST = 910,
    REMOVE_AREA_USING_TARGET_CELL = 911,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_ACTION_COST = 912,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_CHARACTERISTIC = 913,
    BOMB_COOLDOWN_LOSS_FUNCTION_PA_PM = 914,
    EXECUTE_TRIGGER_IN_EFFECT_ZONE = 915,
    MODIFY_DMG_IN_PERCENT_FUNCTION_INITIATIVE = 916,
    HP_STASIS_LOSS = 917,
    DMG_STASIS_GAIN_PERCENT = 918,
    ROLLBACK_TRIGGERING_SPELL_AP_COST = 919,
    ROLLBACK_TRIGGERING_SPELL_MP_COST = 920,
    ROLLBACK_TRIGGERING_SPELL_WP_COST = 921,
    HP_LOSS_PERCENT_OF_VALUE = 922,
    EXECUTE_ACTION_COST = 923,
    CHARAC_SET_AREA_HP = 924,
    AREA_HP_GAIN = 925,
    INIT_BOOST = 926,
    RES_STASIS_LOSS_PERCENT = 927,
    CHARAC_BUFF_BASED_ON_OTHER_CHARAC_VALUE = 928,
    CHARAC_SET_AP = 929,
    CHARAC_SET_INIT = 930,
    REPLACE_TARGET_BY_OWNER = 931,
    DECURSE_LINKED_TO_CASTER = 932,
    CHANGE_PLAYER_SPELLS_BY_MONSTER_ONES = 933,
    EXCLUDE_FROM_FIGHT = 934,
    REMOVE_ALL_AREAS_WITH_ID = 935,
    SPAWN_MONSTER = 936,
    REMOVE_FROM_FIGHT_MAP = 937,
    REG_EXECUTION_COUNT_FUNCTION_TRIGGERING_ACTION_COST = 938,
    HP_LOSS_STASIS_EXPONENTIAL_GROWTH = 939,
    HP_LOSS_FIRE_EXPONENTIAL_GROWTH = 940,
    HP_LOSS_EARTH_EXPONENTIAL_GROWTH = 941,
    HP_LOSS_AIR_EXPONENTIAL_GROWTH = 942,
    HP_LOSS_WATER_EXPONENTIAL_GROWTH = 943,
    RES_WATER_MODIFIED_BY_ARMOR_PLATE = 944,
    RES_AIR_MODIFIED_BY_ARMOR_PLATE = 945,
    RES_EARTH_MODIFIED_BY_ARMOR_PLATE = 946,
    RES_FIRE_MODIFIED_BY_ARMOR_PLATE = 947,
    SET_CHRAGE_TO_DMG_RATIO = 948,
    REG_EXECUTION_COUNT_FIXED = 949,
    SET_AP = 950,
    SET_MP = 951,
    SET_WP = 952,
    DEBUFF_FUMBLE_RATE = 953,
    SET_MICROBOT_RAILS_MAX_DISTANCE = 954,
    VIRTUAL_HP_BOOST_IN_PERCENT_FUNCTION_ALLIES_COUNT = 955,
    VIRTUAL_HP_BOOST_IN_PERCENT = 956,
    SET_VIRTUAL_HP_FROM_HP = 957,
    HP_LOSS_IN_PERCENT_MAX_WITH_VIRTUAL = 958,
    HP_LOSS_IN_PERCENT_MAX_CASTER_WITH_VIRTUAL = 959,
    HP_LOSS_FIRE_FUNCTION_FIGHTER_LEVEL = 960,
    HP_LOSS_EARTH_FUNCTION_FIGHTER_LEVEL = 961,
    HP_LOSS_WATER_FUNCTION_FIGHTER_LEVEL = 962,
    HP_LOSS_AIR_FUNCTION_FIGHTER_LEVEL = 963,
    HP_LOSS_STASIS_FUNCTION_FIGHTER_LEVEL = 964,
    ADD_SPELL_TO_TEMPORARY_SPELL_INVENTORY = 965,
    PLANTATION_BONUS_PLANT = 966,
    PLANTATION_BONUS_TREE = 967,
    PLANTATION_BONUS_CULTIVATION = 968,
    PLANTATION_BONUS_MOB = 969,
    CRAFT_CRAFT_XP_BONUS = 970,
    COLLECT_BONUS_PLANT = 971,
    COLLECT_BONUS_TREE = 972,
    COLLECT_BONUS_CULTIVATION = 973,
    COLLECT_BONUS_MOB = 974,
    COLLECT_BONUS_MINERAL = 975,
    COLLECT_BONUS_FISH = 976,
    CRAFT_QUICKNESS_BONUS = 977,
    PLANTATION_BONUS_TREASURE = 978,
    ALL_ELEMENTAL_SPELL_GAIN = 979,
    PASSIVE_SPELL_GAIN = 980,
    ACTIVE_SUPPORT_SPELL_GAIN = 981,
    REMOVE_PASSIVE_SPELLS = 982,
    AP_SET_TO_MAX = 983,
    SET_VITUAL_HP = 984,
    VIRTUAL_HP_SET_TO_MAX = 985,
    UPDATE_HP_MAX_PERCENT_MODIFIER = 986,
    ADD_BONUS_LOOT = 987,
    CRITICAL_RES_GAIN = 988,
    UPDATE_VIRTUAL_HP_MAX_PERCENT_MODIFIER = 989,
    HP_GAIN_FOR_UNDEAD = 990,
    KO_TIME_BEFORE_DEATH_BUFF = 991,
    TELEPORT_CASTER_BEHIND_TARGET = 992,
    CHANGE_SPELL_TARGET_CELL_BY_CASTER_CELL = 993,
    SUMMON_DOUBLE_FOR_ICE_STATUE = 994,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_SPELL = 995,
    OSA_INVOCATION_KNOWLEDGE_GAIN = 996,
    VIRTUAL_ARMOR_FLAT = 997,
    DMG_WATER_PERCENT_GAIN_FCT_CASTER_DMG_EARTH_PERCENT = 998,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_CHARACTER_LEVEL = 999,
    CHANGE_TRIGERRING_EFFECT_TARGET = 1000,
    COPY_CHARAC_AT_APPLICATION_VALUE = 1001,
    SUMMON_ZOBAL_DOUBLE = 1002,
    KO_TIME_BEFORE_DEATH_MIN_MODIFICATION = 1003,
    MODIFY_DMG_IN_PERCENT_FUNCTION_DODGE = 1004,
    APPLY_STATE_CAPED_BY_ANOTHER_STATE = 1005,
    REG_SUB_EFFECT_VALUE_FUNCTION_CASTER_AP = 1006,
    REG_SUB_EFFECT_VALUE_FUNCTION_CASTER_MP = 1007,
    SET_EFFECT_AREA_FOR_ORIGINAL_CONTROLLER = 1008,
    MODIFY_HEAL_BONUS_IN_PERCENT_FUNCTION_DODGE = 1009,
    ARMOR_GAIN = 1010,
    ARMOR_LOSS = 1011,
    ARMOR_ELEMENTAL_GAIN = 1012,
    REDUCE_ZONE_EFFECT = 1013,
    COPY_CHARAC_IN_REAL_TIME = 1014,
    BEST_ELEMENT_HP_LOSS = 1015,
    BEST_ELEMENT_HP_GAIN = 1016,
    BEST_ELEMENT_HP_GAIN_FUNCTION_PA_PM = 1017,
    SPECIFIC_FOR_ARMOR_DAMAGE_REBOUND = 1018,
    PVP_BUFF_GAIN = 1019,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TRIGGERING_VALUE = 1020,
    REMOVE_BLOCKING_AREA_USING_TARGET = 1021,
    CRAFT_ECOSYSTEM_XP_BONUS = 1022,
    CRAFT_XP_BONUS = 1023,
    STATE_DECURSE_FOR_HYPERACTION = 1024,
    HP_GAIN_FUNCTION_CASTER_EARTH = 1025,
    HP_GAIN_FUNCTION_CASTER_AIR = 1026,
    HP_GAIN_FUNCTION_CASTER_WATER = 1027,
    HP_GAIN_FUNCTION_CASTER_FIRE = 1028,
    HP_GAIN_FUNCTION_CASTER_PHYSICAL = 1029,
    SET_TEAM_ID = 1030,
    REMOVE_EQUIPMENT_EFFECTS = 1031,
    REMOVE_SET_EFFECTS = 1032,
    SET_STEAMER_BLOCK = 1033,
    STEAMER_BLOCK_PASSIVE_RESIST = 1034,
    STEAMER_BLOCK_DAMAGE_REDIRECTION = 1035,
    WEAKEST_RESIST_GAIN = 1036,
    STEAMER_DAMAGE_REDIRECTION = 1037,
    ADD_CHARAC_VALUE_TO_ANOTHER_IN_REAL_TIME = 1038,
    CHARAC_SET_LEADERSHIP = 1039,
    SET_RESISTANCE_TARGET = 1040,
    REG_EXECUTION_COUNT_FUNCTION_ALLIES_COUNT = 1041,
    BARRIER_ELEMENTAL_GAIN = 1042,
    UPDATE_TACKLE_HP_MAX_PERCENT_MODIFIER = 1043,
    CHANGE_AREA_POSITION = 1044,
    MODIFY_RES_IN_PERCENT_FUNCTION_TACKLE = 1045,
    ADD_TO_AI_PRIORITY_TARGETS = 1046,
    RUNNING_EFFECT_GROUP_LEVEL_FUNCTION_TOTAL_HP = 1047,
    DIVIDE_HP_LOSS_UNLESS_THRESHOLD = 1048,
    SWITCH_CHARAC_VALUES = 1049,
    AOE_DMG_GAIN = 1050,
    SINGLE_TARGET_DMG_GAIN = 1051,
    MELEE_DMG_GAIN = 1052,
    RANGED_DMG_GAIN = 1053,
    NON_CRIT_DMG_GAIN = 1054,
    BERSERK_DMG_GAIN = 1055,
    CRITICAL_BONUS_LOSS = 1056,
    SINGLE_TARGET_DMG_LOSS = 1057,
    AOE_DMG_LOSS = 1058,
    MELEE_DMG_LOSS = 1059,
    RANGED_DMG_LOSS = 1060,
    BERSERK_DMG_LOSS = 1061,
    CRITICAL_RES_LOSS = 1062,
    RES_BACKSTAB_LOSS = 1063,
    LEADERSHIP_LOSS = 1064,
    SPELL_WITH_PROPERTY_AP_COST_REDUCTION = 1065,
    SPELL_WITH_PROPERTY_RANGE_GAIN = 1066,
    TACKLE_ACTION_COST = 1067,
    VARIABLE_ELEMENTS_DAMAGE_GAIN = 1068,
    VARIABLE_ELEMENTS_RES_GAIN = 1069,
    ADD_CHARAC_VALUE_TO_ANOTHER_IN_REAL_TIME_WITH_THRESHOLD = 1070,
    VIRTUAL_HP_BOOST = 1071,
    REVERSI_CHECK_FOR_REVERSABLE = 1072,

}